# Elementary States and Properties

## Some basics calculations on three initial states (vacuum, thermal and squeezed)

##### qgt used as a module.py file

In [1]:
import numpy as np
import qgt

In [2]:
vacuum = qgt.Gaussian_state("vacuum", 2)
thermal = qgt.elementary_states("thermal", [4.5, 5.2, 5.75])
squeezed = qgt.elementary_states("squeezed", [1.5 ])

print(f"Vacuum State: {vacuum}\n")
print(f"Thermal State: {thermal}\n")
print(f"Squeezed state: {squeezed}\n")

Vacuum State: 2-mode gaussian state with mean quadrature vector R =
[[0.]
 [0.]
 [0.]
 [0.]]
and covariance matrix V =
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Thermal State: 3-mode gaussian state with mean quadrature vector R =
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
and covariance matrix V =
[[10.   0.   0.   0.   0.   0. ]
 [ 0.  10.   0.   0.   0.   0. ]
 [ 0.   0.  11.4  0.   0.   0. ]
 [ 0.   0.   0.  11.4  0.   0. ]
 [ 0.   0.   0.   0.  12.5  0. ]
 [ 0.   0.   0.   0.   0.  12.5]]

Squeezed state: 1-mode gaussian state with mean quadrature vector R =
[[0.]
 [0.]]
and covariance matrix V =
[[ 0.04978707  0.        ]
 [ 0.         20.08553692]]



In [3]:
# Some properties of the states before any transformation
states = {"Vacuum": vacuum, "Thermal": thermal, "Squeezed": squeezed}

for name, state in states.items():
    print(f"Symplectic eigenvalues of the {name} state:\n{state.symplectic_eigenvalues()}\n")
    print(f"Von Neumann entropy of the {name} state:\n{state.von_Neumann_Entropy()}\n")
    print(f"Purity of the {name} state:\n{state.purity()}\n")
    print(f"Average occupation number of the {name} state:\n{state.occupation_number()}\n\n")

Symplectic eigenvalues of the Vacuum state:
[[1.]
 [1.]]

Von Neumann entropy of the Vacuum state:
5.75453328741913e-14

Purity of the Vacuum state:
1.0000000000000007

Average occupation number of the Vacuum state:
[[0.]
 [0.]]


Symplectic eigenvalues of the Thermal state:
[[10. ]
 [11.4]
 [12.5]]

Von Neumann entropy of the Thermal state:
11.799023283467903

Purity of the Thermal state:
0.0007017543859649119

Average occupation number of the Thermal state:
[[4.5 ]
 [5.2 ]
 [5.75]]


Symplectic eigenvalues of the Squeezed state:
[[1.]]

Von Neumann entropy of the Squeezed state:
2.877266643709565e-14

Purity of the Squeezed state:
1.0000000000000002

Average occupation number of the Squeezed state:
[[4.533831]]


